/** Thuật ngữ thống nhất — tooltip cho toàn app */

export const GLOSSARY = {
  thiTruong: "Thị trường tour — ví dụ: Thái Lan, Châu Âu, Du thuyền.",
  tuyenTour: "Tuyến tour — phân loại chi tiết trong cùng thị trường.",
  tenTour: "Tên Tour — mỗi dòng là 1 sản phẩm tour.",
  congTy: "Tên Công Ty — đại lý/tổ chức bán tour.",
  diemKhoiHanh: "Điểm khởi hành — nơi khách lên tour.",
  thoiGian: "Thời gian — số ngày/đêm của sản phẩm tour.",
  lichKhoiHanh: "Lịch khởi hành — mỗi ngày/đợt trong lịch = 1 đoàn.",
  doanThang: "Tổng số đoàn khởi hành ước tính trong 1 tháng (cộng tất cả sản phẩm).",
  tbDoanThang: "TB số đoàn/tháng/sản phẩm — tần suất khởi hành dùng để so sánh.",
  thiPhanDoan: "% tổng đoàn/tháng của nhóm so với toàn hệ thống.",
  tanSuat: "Tần suất khởi hành = TB số đoàn/tháng/sản phẩm, ước tính từ Lịch khởi hành.",
  tanSuatThu: "Phân bổ đoàn KH theo thứ trong tuần — từ ngày cố định hoặc lịch theo thứ trong Lịch khởi hành.",
  giaTbTour: "Giá TB tour — trung bình có trọng số theo số đoàn; cắt biên 10% khi chênh luxury/phổ thông lớn.",
  giaTbNgay: "Giá TB/ngày = Σ(giá tour × đoàn) ÷ Σ(đoàn × ngày) trên tuyến.",
  giaThiTruong: "Giá thị trường = Giá TB/ngày TT × Số ngày TB thị trường (cùng tuyến).",
  giaTbVtr: "Giá TB VTR = Giá TB/ngày VTR × Số ngày TB VTR (gộp mọi SP trên tuyến, trọng số theo đoàn).",
  giaSoSanh: "Giá so sánh = Giá TB/ngày TT × Số ngày TB VTR (cùng tuyến, quy về độ dài VTR).",
  chenhGia: "Chênh % = Giá TB tour VTR ÷ Giá so sánh − 1. Âm = VTR rẻ hơn.",
  scatterGia: "Mỗi điểm = 1 nhóm so sánh. Màu: xanh VTR rẻ hơn TT, đỏ đắt hơn. Cỡ điểm = TB đoàn/tháng VTR.",
  reNhat: "Tour rẻ nhất thị trường cùng giai đoạn khởi hành với VTR (±45 ngày).",
  segment: "Nhóm so sánh = cùng Thị trường + Tuyến tour + Điểm khởi hành (gộp mọi SP/thời gian). Số hiển thị: tuyến SO SÁNH ĐƯỢC (cả VTR và TT cùng có SP → tính được chênh giá) / tổng tuyến VTR khai thác. Tuyến VTR khai thác mà TT chưa có SP → không tính chênh giá, không vào biểu đồ.",
  methodologyCompare: "Gom theo tuyến + thị trường. Số ngày TB và giá TB/ngày có trọng số theo số đoàn × số ngày từng SP.",
  methodologyMarket: "Phân tích toàn thị trường theo sản phẩm tour. Giá TB robust; thị phần theo tổng đoàn/tháng.",
  methodologyPrice: "Min / TB / Median / Max theo nhóm. TB có trọng số đoàn, giảm ảnh hưởng outlier giá.",
} as const;

export const COL = {
  thiTruong: "Thị trường",
  tuyenTour: "Tuyến tour",
  tenTour: "Tên Tour",
  congTy: "Tên Công Ty",
  diemKhoiHanh: "Điểm khởi hành",
  thoiGian: "Thời gian",
  gia: "Giá",
  lichKhoiHanh: "Lịch khởi hành",
  linkTour: "Link tour",
  doanThang: "Đoàn/tháng",
  tbDoanThang: "TB đoàn/tháng",
  giaTbTour: "Giá TB tour",
  giaTbNgay: "Giá TB/ngày",
  giaThiTruong: "Giá thị trường",
  giaSoSanh: "Giá so sánh",
  giaTbVtr: "Giá TB VTR",
  chenhPct: "Chênh %",
  ngayTb: "Số ngày TB",
  sanPham: "Sản phẩm",
  thiPhanDoan: "Thị phần đoàn",
} as const;
