/** Thuật ngữ thống nhất — tooltip cho toàn app */

export const GLOSSARY = {
  thiTruong: "Thị trường tour — ví dụ: Thái Lan, Châu Âu, Du thuyền.",
  tuyenTour: "Tuyến tour — phân loại chi tiết trong cùng thị trường.",
  tenTour: "Tên Tour — mỗi dòng là 1 sản phẩm tour.",
  congTy: "Tên Công Ty — đại lý/tổ chức bán tour.",
  diemKhoiHanh: "Điểm khởi hành — nơi khách lên tour.",
  thoiGian: "Thời gian — số ngày/đêm của sản phẩm tour.",
  lichKhoiHanh: "Lịch khởi hành — mỗi ngày/đợt trong lịch = 1 đoàn.",
  doanThang: "Tổng số đoàn khởi hành ước tính trong 1 tháng (cộng tất cả sản phẩm).",
  tbDoanThang: "TB số đoàn/tháng/sản phẩm — tần suất khởi hành dùng để so sánh.",
  thiPhanDoan: "% tổng đoàn/tháng của nhóm so với toàn hệ thống.",
  tanSuat: "Tần suất khởi hành = TB số đoàn/tháng/sản phẩm, ước tính từ Lịch khởi hành.",
  giaTbTour: "Giá TB tour — trung bình có trọng số theo số đoàn; cắt biên 10% khi chênh luxury/phổ thông lớn.",
  giaTbNgay: "Giá TB/ngày = Giá tour ÷ Số ngày, có trọng số theo đoàn.",
  giaThiTruong: "Giá thị trường = Giá TB/ngày × Số ngày TB (cùng nhóm sản phẩm).",
  giaTbVtr: "Giá TB Vietravel — TB giá tour VTR có trọng số theo đoàn trong nhóm so sánh.",
  giaSoSanh: "Giá so sánh = Giá TB/ngày thị trường × Số ngày TB Vietravel (cùng điều kiện tuyến).",
  chenhGia: "Chênh % = Giá TB VTR ÷ Giá so sánh − 1. Âm = VTR rẻ hơn.",
  reNhat: "Tour rẻ nhất thị trường cùng giai đoạn khởi hành với VTR (±45 ngày).",
  segment: "Nhóm so sánh: cùng Thị trường + Tuyến tour + Điểm khởi hành (gộp mọi số ngày trên tuyến).",
  methodologyCompare: "So sánh cùng tuyến/điểm KH. Số ngày TB = TB có trọng số đoàn trên tuyến. Tần suất so với đối thủ cao nhất.",
  methodologyMarket: "Phân tích toàn thị trường theo sản phẩm tour. Giá TB robust; thị phần theo tổng đoàn/tháng.",
  methodologyPrice: "Min / TB / Median / Max theo nhóm. TB có trọng số đoàn, giảm ảnh hưởng outlier giá.",
} as const;

export const COL = {
  thiTruong: "Thị trường",
  tuyenTour: "Tuyến tour",
  tenTour: "Tên Tour",
  congTy: "Tên Công Ty",
  diemKhoiHanh: "Điểm khởi hành",
  thoiGian: "Thời gian",
  gia: "Giá",
  lichKhoiHanh: "Lịch khởi hành",
  linkTour: "Link tour",
  doanThang: "Đoàn/tháng",
  tbDoanThang: "TB đoàn/tháng",
  giaTbTour: "Giá TB tour",
  giaTbNgay: "Giá TB/ngày",
  giaThiTruong: "Giá thị trường",
  giaSoSanh: "Giá so sánh",
  giaTbVtr: "Giá TB VTR",
  chenhPct: "Chênh %",
  ngayTb: "Số ngày TB",
  sanPham: "Sản phẩm",
  thiPhanDoan: "Thị phần đoàn",
} as const;
